### ISSUE TITLE
Stamm 3 of the Nordmensa missing in categories.json

### ISSUE THREAD

**Issue by ghost** [stefandesu/goe-mensa-api#3]
The goe-mensa-bot does not show the _Stamm 3_ menu of the _Nordmensa,_ as it is not listed as a category in **data/categories.json**. Is the fix of this issue as simple as adding an entry for Stamm 3 to this file or is further work requiered to solve the problem?

**Comment by stefandesu** [comment]
Sorry for replying this late, I didn't get notified about the issue and haven't worked on the project for a while!

By coincidence, I added *Stamm 3* today because I happened to see it missing. In fact, it was just adding an entry in the file, so if you see anything else missing, feel free to submit a pull request. :)
